### ISSUE TITLE
Slide 30 Playbook Update

### ISSUE THREAD

**Issue by marcusmcpeek** [aristanetworks/ci-workshops-avd#16]
Slide 30 in the Arista CI Workshop 2023 - Presenter Deck has a task for "Import Global Vars". This is no longer needed since we are using the global_vars plugin.  The repo playbook has already been updated.  Just the slide needs to be updated

**Comment by mthiel117** [comment]
Thanks Marcus.  I will get this changed...

**Comment by mthiel117** [comment]
Completed....
